### ISSUE TITLE
Using gpbo in Jupyter Notebook

### ISSUE THREAD

**Issue by a-z-e-r-i-l-a** [markm541374/gpbo#3]
I tried on of the examples by just copying the codes from the python file to a Jupyter Notebook cell and it gives the following error. But if I just use it in the command line it works. I there a way that I use it in Jupyter?

```
import gpbo
import scipy as sp


#dimensionality
D=2
#noise variance
s=1e-6
#number of step to take
n=100

#define a simple 2d objective in x which also varies with respect to the environmental variable
def f(x,**ev):
    y=-sp.cos(x[0])-sp.cos(x[1])+2
    #fixed cost
    c=1.
    #noise
    n = sp.random.normal()*1e-3
    #we want to check the noiseless value when evaluating performance
    if 'cheattrue' in ev.keys():
        if ev['cheattrue']:
            n=0
    print('f inputs x:{} ev:{} outputs y:{} (n:{}) c:{}'.format(x,ev,y+n,n,c))
    return y+n,c,dict()

#arguments to generate default config are objective function, dimensionality, number of steps, noise variance, result directory and result filename
C=gpbo.core.config.eihypgamma(f,D,n,s,'results','eihyp.csv')
out = gpbo.search(C)
print(out)`
```

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-83-8e421b82a0a1> in <module>
>      26 #arguments to generate default config are objective function, dimensionality, number of steps, noise variance, result directory and result filename
>      27 C=gpbo.core.config.eihypgamma(f,D,n,s,'results','eihyp.csv')
> ---> 28 out = gpbo.search(C)
>      29 print(out)
> 
> ~/.local/share/virtualenvs/HesBO-qpst6LpL/lib/python3.6/site-packages/gpbo/core/optimize.py in search(optconfig, initdata)
>     305                                      optconfig.ojfchar,optconfig.chooser,optconfig.choosepara,initdata=initdata)
>     306 
> --> 307     return O.run()
>     308 
>     309 
> 
> ~/.local/share/virtualenvs/HesBO-qpst6LpL/lib/python3.6/site-packages/gpbo/core/optimize.py in run(self)
>     113             mode,self.choosepersist,chooseaux = wrap(self.choosefn,self.state,self.choosepersist,**self.choosepara)
>     114             self.aqpara[mode]['choosereturn']=chooseaux
> --> 115             x,ev,self.aqpersist[mode],aqaux = wrap(self.aqfn[mode],self.state,self.aqpersist[mode],**self.aqpara[mode])
>     116             t1 = time.clock()
>     117             self.state.aux = aqaux
> 
> ~/.local/share/virtualenvs/HesBO-qpst6LpL/lib/python3.6/site-packages/gpbo/core/optimize.py in wrap(fn, optstate, persist, **para)
>     267         if optstate.condition>-20:
>     268             logger.info('using raised noise floor {} in {}'.format(optstate.condition,fn))
> --> 269         return fn(optstate,persist,**para)
>     270     except gpbo.core.GPdc.GPdcError as e:
>     271         traceback.print_exc()
> 
> gpbo/core/acquisitions.pyx in gpbo.core.acquisitions.eihypaq (gpbo/core/acquisitions.c:10010)()
> 
> gpbo/core/optutils.pyx in gpbo.core.optutils.twopartopt (gpbo/core/optutils.c:15787)()
> 
> gpbo/core/optutils.pyx in gpbo.core.optutils.silentdirectwrapped (gpbo/core/optutils.c:14975)()
> 
> gpbo/core/optutils.pyx in gpbo.core.optutils.silentdirect (gpbo/core/optutils.c:13317)()
> 
> TypeError: an integer is required (got type OutStream)

**Comment by markm541374** [comment]
I'm afraid I have only every used command line.
