### ISSUE TITLE
csv file columns meaning

### ISSUE THREAD

**Issue by a-z-e-r-i-l-a** [markm541374/gpbo#4]
Hi,

I wanted to ask about the meaning of the columns of the csv file that is saved after using the gpbo.

For example "truey at xrecc" or " y"  and their difference or the " taq", "tev" column.

In addition, so far I tried reading the csv file with pandas which had some issues and I appreciate if you had a recommendation on how might be the best way to read it especially for reading the observation (or best solution) at each evaluation step and teh input x value for it.

Thanks.
Alireza

**Comment by markm541374** [comment]
Hi Alireza,
The meanings are as follows,
"truey at xrecc" The true value of the objective function at the posterior mean of the trained GP
"y" The observed function value at [x0, x1, x2...]
"taq" The cpu time of the acquisition function
"tev" The cpu time of evaluation the objective.

I'm afraid I can't be of much help reading the file as I've had no issue using pandas.read_csv
